define the access token paths, both private and public
access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
// define the refresh token paths
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
spring:
  profiles:
    active: dev
Connect to the Mysql database
  data:
    mysql:
      uri: jdbc:mysql://${MYSQL_HOST}:${MYSQLDB_PORT}/?authSource=${MYSQLDB_DB}
      database: ${MYSQLDB_DB}
logging:
  level:
    org.springframework.security: DEBUG

